css_dir = "css" # by Fire.app
sass_dir = "_sass" # by Fire.app
images_dir = "img" # by Fire.app
javascripts_dir = "javascripts" # by Fire.app
fireapp_coffeescripts_dir = "coffeescripts" # by Fire.app
fireapp_livescripts_dir = "livescripts" # by Fire.app
fireapp_minifyjs_on_build = false # by Fire.app
fireapp_always_report_on_build = false # by Fire.app
output_style = :expanded # by Fire.app
relative_assets = false # by Fire.app
line_comments = true # by Fire.app
sass_options = {:debug_info=>false} # by Fire.app
sourcemap = false # by Fire.app
fireapp_coffeescript_options = {:bare=>true} # by Fire.app
fireapp_livescript_options = {:bare=>true} # by Fire.app
